export EDITOR="code"
export NVM_DIR="${HOME}/.nvm"
export ANDROID_SDK_ROOT="${HOME}/Library/Android/sdk"
export PATH="${ANDROID_SDK_ROOT}/platform-tools:${PATH}"
export PATH="${HOME}/.platformio/penv/bin:${PATH}"
